version: '3.8'
services:
 app:
  build: .
  ports:
    - "9091:9091"
  restart: always
  depends_on:
        - postgres
  
 postgres:
      image: postgres:16.4
      container_name: postgres_container
      environment:
        POSTGRES_USER: avnadmin
        POSTGRES_PASSWORD: ${AIVEN_PG_PASSWORD}
        POSTGRES_DB: defaultdb
      ports:
        - "23962:23962"
      volumes:
        - postgres_data:/var/lib/postgresql/data